In [ ]:
import seaborn as sns 
df = sns.load_dataset("titanic")

In [2]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Rasulbek907\Desktop\Project_One\Data\Raw_Data\atlanta_9-24-2016_9-30-2017.csv")

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Commodity Name   57 non-null     object
 1   City Name        57 non-null     object
 2   Type             0 non-null      float64
 3   Package          57 non-null     object
 4   Variety          57 non-null     object
 5   Sub Variety      1 non-null      object
 6   Grade            0 non-null      float64
 7   Date             57 non-null     object
 8   Low Price        57 non-null     float64
 9   High Price       57 non-null     float64
 10  Mostly Low       57 non-null     float64
 11  Mostly High      57 non-null     float64
 12  Origin           57 non-null     object
 13  Origin District  0 non-null      float64
 14  Item Size        56 non-null     object
 15  Color            0 non-null      float64
 16  Environment      0 non-null      float64
 17  Unit of Sale     0 non-null      float64
 18  Quality          0 non-null      float64
 19  Condition        0 non-null      float64
 20  Appearance       0 non-null      float64
 21  Storage          0 non-null      float64
 22  Crop             0 non-null      float64
 23  Repack           57 non-null     object
 24  Trans Mode       0 non-null      float64
dtypes: float64(16), object(9)
memory usage: 11.3+ KB

In [20]:
df.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,ATLANTA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,140.0,154.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,ATLANTA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,145.0,154.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,ATLANTA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150.0,154.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,ATLANTA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150.0,150.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,ATLANTA,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,140.0,154.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

# Datani Split qilish

# Dataset 3 ta qismga bo`linadi
- 1-qism : Train - yani modelni o`qitish uchun   == 80%  yoki 70 % 
- 2-qism : Test - yani modelni test qilib korish uchun  == 10 %  == yoki == 15 % 
- 3-qism : Validation - yani modelni baholab olish uchun == 10% == yoki == 15 %

In [23]:
df

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,col_female,col_male,col_C,col_Q,col_S
0,0,1,0,0.827377,-1.310217,-0.592481,0.432793,-0.473674,0.918966,-0.502445,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
1,1,2,1,-1.566107,-0.991410,0.638789,0.432793,-0.473674,1.282625,0.786845,1.161545,1.355574,-1.355574,2.074505,-0.307562,-1.623803
2,2,3,1,0.827377,-0.357685,-0.284663,-0.474545,-0.473674,1.646283,-0.488854,-0.281881,1.355574,-1.355574,-0.482043,-0.307562,0.615838
3,3,4,1,-1.566107,-0.672604,0.407926,0.432793,-0.473674,-1.442322,0.420730,0.057748,1.355574,-1.355574,-0.482043,-0.307562,0.615838
4,4,5,0,0.827377,-1.671790,0.407926,-0.474545,-0.473674,0.664904,-0.486337,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,-0.369365,0.400452,-0.207709,-0.474545,-0.473674,-1.183277,-0.386671,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
887,887,888,1,-1.566107,-0.552079,-0.823344,-0.474545,-0.473674,-1.616678,-0.044381,-1.003594,1.355574,-1.355574,-0.482043,-0.307562,0.615838
888,888,889,0,0.827377,-0.124412,0.000000,0.432793,2.008933,1.676173,-0.176263,-0.281881,1.355574,-1.355574,-0.482043,-0.307562,0.615838
889,889,890,1,-1.566107,-1.415189,-0.284663,-0.474545,-0.473674,-1.646568,-0.044381,0.270017,-0.737695,0.737695,2.074505,-0.307562,-1.623803
890,890,891,0,0.827377,-0.874774,0.177063,-0.474545,-0.473674,0.635014,-0.492378,-0.281881,-0.737695,0.737695,-0.482043,3.251373,-1.623803

# Feature Va Targetga ajratish

In [24]:
x = df.drop(columns=["Cabin"])
y = df["Cabin"]

In [5]:
y

0     -0.281881
1      1.161545
2     -0.281881
3      0.057748
4     -0.281881
         ...
886   -0.281881
887   -1.003594
888   -0.281881
889    0.270017
890   -0.281881
Name: Cabin, Length: 891, dtype: float64

In [6]:
x

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,col_female,col_male,col_C,col_Q,col_S
0,0,1,0,0.827377,-1.310217,-0.592481,0.432793,-0.473674,0.918966,-0.502445,-0.737695,0.737695,-0.482043,-0.307562,0.615838
1,1,2,1,-1.566107,-0.991410,0.638789,0.432793,-0.473674,1.282625,0.786845,1.355574,-1.355574,2.074505,-0.307562,-1.623803
2,2,3,1,0.827377,-0.357685,-0.284663,-0.474545,-0.473674,1.646283,-0.488854,1.355574,-1.355574,-0.482043,-0.307562,0.615838
3,3,4,1,-1.566107,-0.672604,0.407926,0.432793,-0.473674,-1.442322,0.420730,1.355574,-1.355574,-0.482043,-0.307562,0.615838
4,4,5,0,0.827377,-1.671790,0.407926,-0.474545,-0.473674,0.664904,-0.486337,-0.737695,0.737695,-0.482043,-0.307562,0.615838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,-0.369365,0.400452,-0.207709,-0.474545,-0.473674,-1.183277,-0.386671,-0.737695,0.737695,-0.482043,-0.307562,0.615838
887,887,888,1,-1.566107,-0.552079,-0.823344,-0.474545,-0.473674,-1.616678,-0.044381,1.355574,-1.355574,-0.482043,-0.307562,0.615838
888,888,889,0,0.827377,-0.124412,0.000000,0.432793,2.008933,1.676173,-0.176263,1.355574,-1.355574,-0.482043,-0.307562,0.615838
889,889,890,1,-1.566107,-1.415189,-0.284663,-0.474545,-0.473674,-1.646568,-0.044381,-0.737695,0.737695,2.074505,-0.307562,-1.623803
890,890,891,0,0.827377,-0.874774,0.177063,-0.474545,-0.473674,0.635014,-0.492378,-0.737695,0.737695,-0.482043,3.251373,-1.623803

# Train va Temporary split == 70% ga 30 %

In [27]:
from sklearn.model_selection import train_test_split
x_train, x_temp, y_train, y_temp = train_test_split (x, y, test_size=0.3, random_state=42)

In [29]:
x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size=0.5, random_state=42)

In [30]:
x_val

,Unnamed: 0,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,col_female,col_male,col_C,col_Q,col_S
377,377,378,-1.566107,1.621247,-0.207709,-0.474545,2.008933,-1.551917,3.610065,1.076638,-0.737695,0.737695,2.074505,-0.307562,-1.623803
244,244,245,0.827377,-1.547377,0.023154,-0.474545,-0.473674,-0.625336,-0.502949,-0.281881,-0.737695,0.737695,2.074505,-0.307562,-1.623803
72,72,73,-0.369365,-0.268264,-0.669435,-0.474545,-0.473674,1.407165,0.831478,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
815,815,816,-1.566107,-0.684267,0.000000,-0.474545,-0.473674,-1.611697,-0.648422,-1.597946,-0.737695,0.737695,-0.482043,-0.307562,0.615838
841,841,842,-0.369365,0.462658,-1.054207,-0.474545,-0.473674,1.397202,-0.437007,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,444,445,0.827377,-0.167179,0.000000,-0.474545,-0.473674,0.799407,-0.485079,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
764,764,765,0.827377,-0.824231,-1.054207,-0.474545,-0.473674,-0.057431,-0.491874,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
743,743,744,0.827377,0.314919,-0.438572,0.432793,-0.473674,0.689812,-0.324253,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
263,263,264,-1.566107,-0.408228,0.792698,-0.474545,-0.473674,-1.606715,-0.648422,-0.324335,-0.737695,0.737695,-0.482043,-0.307562,0.615838
730,730,731,-1.566107,-1.675678,-0.053800,-0.474545,-0.473674,-0.984013,3.606793,-0.918687,1.355574,-1.355574,-0.482043,-0.307562,0.615838

In [31]:
y_val

377    0
244    0
72     0
815    0
841    0
      ..
444    1
764    0
743    0
263    0
730    1
Name: Survived, Length: 134, dtype: int64

In [32]:
x_temp

,Unnamed: 0,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,col_female,col_male,col_C,col_Q,col_S
625,625,626,-1.566107,1.356871,2.408739,-0.474545,-0.473674,0.580216,0.002348,2.392703,-0.737695,0.737695,-0.482043,-0.307562,0.615838
566,566,567,0.827377,1.325768,-0.823344,-0.474545,-0.473674,0.067109,-0.489442,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
459,459,460,0.827377,0.614286,0.000000,-0.474545,-0.473674,0.644977,-0.492378,-0.281881,-0.737695,0.737695,-0.482043,3.251373,-1.623803
804,804,805,0.827377,-0.365461,-0.207709,-0.474545,-0.473674,-0.002633,-0.507982,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
338,338,339,0.827377,-0.983634,1.177469,-0.474545,-0.473674,0.854205,-0.486337,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,184,185,0.827377,-0.015552,-1.977659,-0.474545,2.008933,-0.336402,-0.204955,-0.281881,1.355574,-1.355574,-0.482043,-0.307562,0.615838
607,607,608,-1.566107,-0.956419,-0.207709,-0.474545,-0.473674,-1.437340,-0.034314,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
624,624,625,0.827377,-1.329656,-0.669435,-0.474545,-0.473674,0.779481,-0.324253,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
103,103,104,0.827377,-0.155515,0.254017,-0.474545,-0.473674,0.829297,-0.474172,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
387,387,388,-0.369365,-1.271338,0.484880,-0.474545,-0.473674,-0.590465,-0.386671,-0.281881,1.355574,-1.355574,-0.482043,-0.307562,0.615838

In [33]:
x_test

,Unnamed: 0,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,col_female,col_male,col_C,col_Q,col_S
455,455,456,0.827377,-0.206058,-0.053800,-0.474545,-0.473674,0.201613,-0.489442,-0.281881,-0.737695,0.737695,2.074505,-0.307562,-1.623803
607,607,608,-1.566107,-0.956419,-0.207709,-0.474545,-0.473674,-1.437340,-0.034314,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
142,142,143,0.827377,-0.489873,-0.438572,0.432793,-0.473674,1.641301,-0.329287,-0.281881,1.355574,-1.355574,-0.482043,-0.307562,0.615838
883,883,884,-0.369365,-1.492947,-0.130754,-0.474545,-0.473674,1.128194,-0.437007,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
835,835,836,-1.566107,-1.049728,0.715743,0.432793,0.767630,1.347386,1.025945,3.241777,1.355574,-1.355574,2.074505,-0.307562,-1.623803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,322,323,-0.369365,1.232459,0.023154,-0.474545,-0.473674,-1.068700,-0.399758,-0.281881,1.355574,-1.355574,-0.482043,3.251373,-1.623803
642,642,643,0.827377,1.216907,-2.131568,2.247470,2.008933,-0.007615,-0.086664,-0.281881,1.355574,-1.355574,-0.482043,-0.307562,0.615838
566,566,567,0.827377,1.325768,-0.823344,-0.474545,-0.473674,0.067109,-0.489442,-0.281881,-0.737695,0.737695,-0.482043,-0.307562,0.615838
690,690,691,-1.566107,-0.901989,0.100109,0.432793,-0.473674,-1.243057,0.499256,-1.470585,-0.737695,0.737695,-0.482043,-0.307562,0.615838
823,823,824,0.827377,0.408228,-0.207709,-0.474545,0.767630,0.734646,-0.397241,2.732333,1.355574,-1.355574,-0.482043,-0.307562,0.615838

# Quyidagi holatlarga etibor bergan holda tanlovni amalga oshirish 

- Kichik Dataset -- Train/ Val/ Test 
- Juda Kichik Datset -- Cross Validation 
- Kattaroq Dataset -- 70 / 15 -15  tavsiya qilinadi 
- Deep Learning - Validation qism majburiy

# Modelni o`qitish jarayoni

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

model = LinearRegression()

model.fit(x_train, y_train)

y_val_pred = model.predict(x_val)
val_score = r2_score(y_val, y_val_pred)

print("Validation r2_Score :  ", val_score)

Validation r2_Score :   0.03927057629429498

In [36]:
y_test_pred = model.predict(x_test)
test_accuracy = r2_score(y_test, y_test_pred)

print("Test r2_score: ", test_accuracy)

Test r2_score:  0.12528367710223343

In [37]:
y_train_pred = model.predict(x_train)

train_accuracy = r2_score(y_train, y_train_pred)

print("Train r2_score: ", train_accuracy)

Train r2_score:  0.0790441129685322